spring:
  profiles:
    active: dev
  application:
    name: market-service
  config:
    import: configserver:http://user:pass@localhost:9999

---
# dev profile

spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:marketdb
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: create-drop
    database-platform: org.hibernate.dialect.H2Dialect
  sql:
    init:
      mode: always
  config:
    activate:
      on-profile:
        dev
  h2:
    console:
      enabled: true
      path: /management

server:
  port: 8383